version: '3.8'

services:
  flaskdockerstarterkit:
    image: flaskdockerstarterkit
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    ports:
      - 5000:5000
    volumes:
      - my_volumes:/flask_starterkit:cached  # Mount named volume to container directory
    env_file: .env

  debugger:
    image: debugger
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debugger
    ports:
      - 5001:5000  # Changed host port to avoid conflict
      - 5678:5678
    volumes:
      - my_volumes:/debugger_mount:cached  # Mount named volume to container directory
    env_file: .env

  test-runner:
    image: test-runner
    build:
      context: .
      dockerfile: ./Dockerfile
      target: test
    env_file: .env

volumes:
  my_volumes:  # Define named volume
