name: Unit test

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "reopened"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:                              
      - uses: actions/checkout@v4
      - name: Generate requied .env file
        run: |
          echo DEBUG=True >> .env
          echo FLASK_DEBUG=1 >> .env
          echo FLASK_APP=run.py >> .env
      - name: Building COntainers
        run: docker compose build
      - name: Run tests
        run: docker compose up --abort-on-container-exit test-runner

